id: P005495
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:54:32.436402
source_metadata:
  id: bdr:W19811
  title: གཅོད་ཡུལ་ཉོན་མོངས་ཞི་བྱེད་ཀྱི་བཀའ་གཏེར་བླ་མ་བརྒྱུད་པའི་རྣམ་ཐར་བྱིན་རླབས་གཏེར་མཚོ།
  author: ''
  volumes:
    03eaaeadb505436ba1ca0f6f18b87542:
      image_group_id: I5970
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
